dist: trusty
language: c
addons:
  apt:
    packages:
    - nasm
script:
- make pinpog
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: P5WyaaXCJdD+Nyuy30WjJ4ybOpJAJEX6ma8yq+zG1uVZir2f2Nrowf25ntE8KEQ6llsE35S+6HWAR3WGtZ5qJYBilTyRNhnVgoENrN6M92mblsH3he0dJ/lkG0POvUHHuqK0lYwu0cx9bRwpLfrG0VRtvE5Mdg7wEOGGIK+QqPAqBsaBhDXBOjeFitU0ccnuXdyOMieQ8paTeRAZlZQMkj4aoeNk1VeSWnK28pb8+CCFxO/15GE0RqOCLMGiK5Ep9j9r1rstLbOUzSeWVwxtdYlXUlaL/G7Spauq/6KoIWMHApe2phn4CsQs3i+1C7f1v6BMCPCXXKB8GHOcR/b+yBpQHM0V7lPDGbEBP/e7ayFMiyeQBlmjlj4cGzChPCjkRkGSKPpiknKxd3a0twzNLE/2ODIYFfksGYUm8rHqX5OitRFT92gGTs9BDKwYJjaVj4+KItADDiR6cs4NOQpkl3vIryOvbT7M3FA6giROesHjk2PUb/tc29jYi1B/+x5mFm5aNOBRPGh+FdZ1MpMrC2DgZtVeqAQyv+lY49kZ9n+MaP3EQiWOOutn4JoQD+fVHl0MQVb2Se4le6b2RgpmCxMGgrqluzivClY+b0hc4gAAzooARMXcMjo5ocw8o2jUpXwq9axdGRLeUvKIPL9sc76Fb8RevvMIE2N2PpijmL4=
  file: pinpog
  on:
    all_branches: true
    repo: mrstock/pinpog
